### ISSUE TITLE
Failed XML deserialization on special XML attributes

### ISSUE THREAD

**Issue by empwilli** [aas-core-works/aas-core3.0-python#44]
The python XML deserialization ensures, that elements won't contain any attributes when parsing the different element types (`_raise_if_has_tail_or_attrib`), this is in accordance with the [spec](https://github.com/admin-shell-io/aas-specs/tree/master/schemas/xml#why-no-xml-attributes) that mandates that the XML representation must not use attributes for modelling purposes.

However, this leads to issues with special XML attributes, currently, aas-core3.0-python, for example, fails to deserialize the following example (Note: the C# SDK has no such check in place and will happily deserialize the document):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<environment
    xmlns="https://admin-shell.io/aas/3/0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://admin-shell.io/aas/3/0/AAS.xsd">
</environment>
```

Interestingly, `xml.etree` does not consider xml namespace attributes as attributes, i.e., if we drop the `xsi:schemaLocation` line, the xmlization can also process the example.

**Comment by mristin** [comment]
Hi @empwilli ! Thanks for reporting! 

Actually, there were related problems with C# and Golang SDKs:
https://github.com/aas-core-works/aas-core3.0-csharp/issues/24
https://github.com/aas-core-works/aas-core3.0-golang/issues/25

Please give me some time -- I hope to be able to fix this till the end of the week.

**Comment by mristin** [comment]
@empwilli : in the meanwhile, could you please double-check -- what should be the correct behavior here -- should attributes from the namespace `xsi` simply be ignored?

Please see this comment and following: https://github.com/aas-core-works/aas-core3.0-golang/issues/25#issuecomment-2112039644

We probably need a similar solution to: https://github.com/aas-core-works/aas-core3.0-golang/issues/25#issuecomment-2114208850

**Comment by empwilli** [comment]
> @empwilli : in the meanwhile, could you please double-check -- what should be the correct behavior here -- should attributes from the namespace xsi simply be ignored?

To my understanding we should at least allow, i.e., ignore, the `xsi:schemaLocation` and `xsi:noNamespaceSchemaLocation`, as they provide means to refer to the AAS XML schema. I'm a little bit conflicted wrt. to `xsi:nil` and `xsi:type`, though, as they allow to change the semantics of the model.

I understand that one has to be careful not to introduce an ever growing list of ignored attributes, though. In a quick google search I could not find further standard attributes that affect schema validation/interpretation of XML documents. So I'd argue to either completely ignore attributes with `xsi` prefix, or, at least to ignore `xsi:schemaLocation` and `xsi:noNamespaceSchemaLocation`.  

Edit: formatting

**Comment by mristin** [comment]
@empwilli would #45 work for you? I suppose filtering the attributes is the most general approach, even though a bit ugly.

**Comment by empwilli** [comment]
Looks fine to me. Thanks!
